"""add groups

Revision ID: 103a097306dc
Revises: f9c55f171c84
Create Date: 2026-05-25 07:06:19.434107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103a097306dc'
down_revision: Union[str, Sequence[str], None] = 'f9c55f171c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_index(op.f('ix_group_statuses_id'), 'group_statuses', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('last_post_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['group_statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=True)
    op.create_index(op.f('ix_groups_status_id'), 'groups', ['status_id'], unique=False)
    op.create_table('user_groups',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.add_column('posts', sa.Column('group_id', sa.BigInteger(), nullable=True))
    op.alter_column('posts', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_foreign_key(None, 'posts', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('posts', 'group_id')
    op.drop_table('user_groups')
    op.drop_index(op.f('ix_groups_status_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_group_statuses_id'), table_name='group_statuses')
    op.drop_table('group_statuses')
    # ### end Alembic commands ###
