"""fix alert unique constraint

Revision ID: 5ee0680462ba
Revises: 103a097306dc
Create Date: 2026-05-25 07:14:51.678876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee0680462ba'
down_revision: Union[str, Sequence[str], None] = '103a097306dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alerts_post_id_key'), 'alerts', type_='unique')
    op.create_unique_constraint('uq_user_post_alert', 'alerts', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_post_alert', 'alerts', type_='unique')
    op.create_unique_constraint(op.f('alerts_post_id_key'), 'alerts', ['post_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
